network_fix_function <- function(input){
  input$network[input$network == "ABC NEWS"] <-"ABC"
  input$network[input$network == "ABC NEWS TRANSCRIPT"] <-"ABC"
  input$network[input$network == "ABC NEWS TRANSCRIPTS"] <-"ABC"
  input$network[input$network == "AMERICAN PUBLIC MEDIA"] <-"APM"
  input$network[input$network == "BLOOMBERG: TV"] <-"BLOOMBERG"
  input$network[input$network == "CBS NEWS TRANSCRIPTS"] <-"CBS"
  input$network[input$network == "CNBC NEWS TRANSCRIPTS"] <-"CNBC"
  input$network[input$network == "CNN"] <-"CNN"
  input$network[input$network == "LOU DOBBS TONIGHT"] <- "FOX_NEWS_BUSINESS"
  input$network[input$network == "CNBC/"] <-"CNBC"
  input$network[input$network == "CNN CNN"] <-"CNN"
  input$network[input$network == "CTV TELEVISION, INC."] <-"CTV"
  input$network[input$network == "FOX NEWS NETWORK"] <-"FOX"
  input$network[input$network == "GLOBAL BROADCAST DATABASE - ENGLISH"] <-"Error"
  input$network[input$network == "MSNBC"] <-"MSNBC"
  input$network[input$network == "NATIONAL PUBLIC RADIO (NPR)"] <-"NPR"
  input$network[input$network == "NBC NEWS TRANSCRIPTS"] <-"NBC"
  input$network[input$network == "ABC TRANSCRIPTS (AUSTRALIA)"] <-"ABC_AUSTRALIA"
  input$network[input$network == "CNN INTERNATIONAL"] <-"CNN_INTERNATIONAL"
  input$network[input$network == "NATIONAL PUBLIC RADIO"] <-"NPR"
  input$network[input$network == "NBC NEWS"] <-"NBC"
  input$network[input$network == "WASHINGTON WEEK"] <-"PBS"
  return(input)
}